<a href="https://colab.research.google.com/github/gggggeun/study/blob/main/1.%20%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0(Scikit_learn)/4.%20%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0%EC%9C%BC%EB%A1%9C_%EC%9D%B8%EC%BD%94%EB%94%A9_%EB%B3%80%ED%99%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encoding

## Label encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
items=['피자','치킨','짜장면','짜장면','탕수육']
encoder= LabelEncoder()
encoder.fit(items)
labels= encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [3 1 0 0 2]


In [ ]:
print('인코딩 클래스 : ', encoder.classes_)
print('디코딩 원본값 : ', encoder.inverse_transform([1,2,3,0]))

인코딩 클래스 :  ['짜장면' '치킨' '탕수육' '피자']
디코딩 원본값 :  ['치킨' '탕수육' '피자' '짜장면']


## One-hot encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['피자','치킨','짜장면','짜장면','탕수육']
#먼저 label encoding을 사용해 숫자값으로 변경
encoder= LabelEncoder()
encoder.fit(items)
labels= encoder.transform(items)
labels

array([3, 1, 0, 0, 2])

In [ ]:
#2차원 데이터로 변환
labels = labels.reshape(-1,1)
labels

array([[3],
       [1],
       [0],
       [0],
       [2]])

In [ ]:
#원핫인코딩
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원 : ',oh_labels.shape)


원-핫 인코딩 데이터
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
원-핫 인코딩 데이터 차원 :  (5, 4)


In [ ]:
import pandas as pd

df = pd.DataFrame({'item' : ['피자','치킨','짜장면','짜장면','탕수육']})
pd.get_dummies(df)

item_짜장면  item_치킨  item_탕수육  item_피자
0         0        0         0        1
1         0        1         0        0
2         1        0         0        0
3         1        0         0        0
4         0        0         1        0