<a href="https://colab.research.google.com/github/gggggeun/study/blob/main/5.%20%EB%94%A5%EB%9F%AC%EB%8B%9D(deep%20learning)/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor

: 다차원 넘파이 배열. 머신러닝 기본 데이터 구조로 사용.



텐서플로를 비롯해 딥러닝 라이브러리들은 다차원 배열을 텐서라고 부른다. (하지만 파이썬 커뮤니티에서 넘파이 배열을 텐서라고 부르지는 않는다.)

텐서는 임의의 차원 개수를 가지는 행렬의 일반화된 모습이다. 텐서에서는 차원(dimension)을 종종 축(axis)라고 부른다.

핵심적으로 텐서는 데이터를 위한 컨테이너(container)이다. 거의 수치형 데이터를 다루므로 숫자를 위한 컨테이너라고 생각하면 된다.

### 텐서의 핵심 속성
- 축의 개수(rank) : 2D = (axis=2), 3D = (axis=3)
- 크기(shape) : 텐서의 각 축을 다라 얼마나 많은 차원이 있는지 나타낸 파이썬의 튜플.  
  ex) 1D = (5,) , 3D = (3, 5) , 3D = (3, 3, 5) 
- 데이터 타입(dtype) : 텐서에 포함된 데이터의 타입. float32, uint8, float64 등. 드물게 char 타입을 사용하지만, 텐서는 사전에 할당되어 연속된 메모리에 저장되어야 하므로 넘파이 배열과 대부분 라이브러리는 가변 길이의 문자열을 지원하지 않는다.

### 1. Scalar - 0D tensor

In [3]:
import numpy as np
x = np.array(12)
x

array(12)

In [6]:
print("rank : ", x.ndim)

rank :  0


### 2. Vector - 1D tensor

In [8]:
x = np.array([1, 10, 55, 25, 9])
x

array([ 1, 10, 55, 25,  9])

In [11]:
print("rank : ", x.ndim)

rank :  1


### 3. Metrix - 2D tensor

In [13]:
x = np.array([[1, 3, 5, 7, 9],
             [39, 23, 22, 1, 0],
             [3, 66, 39, 2, 8]])
x

array([[ 1,  3,  5,  7,  9],
       [39, 23, 22,  1,  0],
       [ 3, 66, 39,  2,  8]])

In [14]:
print("rank : ", x.ndim)

rank :  2


### 4. 3D tensor & High-dimension tensor

In [15]:
x = np.array([[[1, 3, 5, 7, 9],
             [39, 23, 22, 1, 0],
             [3, 66, 39, 2, 8]],
             [[1, 3, 5, 7, 9],
             [39, 23, 22, 1, 0],
             [3, 66, 39, 2, 8]],
             [[1, 3, 5, 7, 9],
             [39, 23, 22, 1, 0],
             [3, 66, 39, 2, 8]]])
x

array([[[ 1,  3,  5,  7,  9],
        [39, 23, 22,  1,  0],
        [ 3, 66, 39,  2,  8]],

       [[ 1,  3,  5,  7,  9],
        [39, 23, 22,  1,  0],
        [ 3, 66, 39,  2,  8]],

       [[ 1,  3,  5,  7,  9],
        [39, 23, 22,  1,  0],
        [ 3, 66, 39,  2,  8]]])

In [16]:
print("rank : ", x.ndim)

rank :  3


3D 텐서들을 하나의 배열로 합치면 4D 텐서가 만들어 진다.

딥러닝에서는 보통 0D에서 4D까지의 텐서를 다룬다. 만약 동영상 데이터를 다룰 경우에는 5D 텐서 까지 가기도 한다.